### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by vrde** [pycco-docs/pycco#103]
Hello maintainer! Any plan to make a new release soonish? I'd like to use [`--skip-bad-files`](https://github.com/pycco-docs/pycco/pull/101) in the project I'm working on :smiley:. If not, I can publish my own release of pycco on Pypi and use that one. Thanks!

**Comment by subsetpark** [comment]
Thanks for the reminder! I’ll cut one in the next couple days.

On lun, lug 16, 2018 at 9:50, vrde <notifications@github.com> wrote:
Hello maintainer! Any plan to make a new release soonish? I'd like to use --skip-bad-files [https://github.com/pycco-docs/pycco/pull/101] in the project I'm working on 😃 . If not, I can publish my own release of pycco on Pypi and use that one. Thanks!

**Comment by subsetpark** [comment]
This has now been done. Apologies for my lateness.
